### ISSUE TITLE
Multiline title

### ISSUE THREAD

**Issue by ruzickap** [spech66/bootstrap-bp-hugo-startpage#1]
Is there any way how to do the "multiline title"? 
Something like (`links.yml`):

```yaml
---
- group: Web pages
  items:
    - title: |
        My blog 
        (myblog.dev)
```

But the example above will give me only single line "My blog (myblog.dev)" in the final rendered web page.
